apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic-dockerfile-empty-private-plgv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic-dockerfile-empty-private-plgv
    app.kubernetes.io/part-of: mc-golang-without
  name: devfile-sample-go-basic-dockerfile-empty-private-plgv
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: devfile-sample-go-basic-dockerfile-empty-private-plgv
status:
  loadBalancer: {}
